### ISSUE TITLE
Does PAGE_2MB_SHIFT equal to 20 or 21?

### ISSUE THREAD

**Issue by YalandHong** [CGCL-codes/HSCC#4]
Hello,

Currently, HSCC sets `PAGE_2MB_SHIFT` to 20, which bewilders me quite a lot.

https://github.com/CGCL-codes/HSCC/blob/4f1754311c513ff637331fd06558565f35ad1944/zsim-nvmain/src/common/global_const.h#L24

In my opinion, if an address is 2MB-aligned, since 2M = 2^21 = 1<<21, you should have set this variable to 21.

Please correct me if I'm wrong. Thanks!

**Comment by haikunliu** [comment]
Hi YaLandHong,

You are right. This is a mistake I will fix soon.

Thanks for your comments.

**Comment by YalandHong** [comment]
By the way, please sync the repositories of Gitee and SHMA. Thank you very much.

I'm closing this issue. However I have actually found some other problems with the code, which I need more information to prove. Maybe I will open another issue if I figure them out.

**Comment by YalandHong** [comment]
The reason why this mistake does not result in severe error is that `PAGE_2MB_SHIFT` is **not used** in any place of HSCC. I searched all the code in my VSCode but could not find any reference to `PAGE_2MB` or `PAGE_2MB_SHIFT`.

Actually, there are some other unused but problematic parts of the code in HSCC, which may trigger unexpected behavior.

**Comment by haikunliu** [comment]
Yes, the codes is not rigorously tested. Thank you for  pointing out those issues.
